#! /bin/sh

tint3 &

bspc config border_width        2
bspc config window_gap          12

bspc config split_ratio         0.62
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config bottom_padding      35

bspc monitor -d Main View Docs Code Proj1 Proj2 Proj3 IQPView IQP Background

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Skype desktop=^7 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Wait one second to run stalonetray so it appears on top of tint3
sleep 1 && stalonetray
