export _JAVA_AWT_WM_NONREPARENTING=1

sxhkd &
feh --bg-scale /WPI/Pictures/backgroundpics/Dragon.JPG &
compton -b --vsync opengl-swc --backend glx -f -D 5 --config /dev/null --inactive-dim 0.25 &

xrandr --dpi 192 &
xrdb .Xresources &

dunst &
nm-applet &
exec bspwm
