alias srcbash='source ~/.bashrc'
alias srczsh='source ~/.zshrc'
alias ls='ls -h --color'
alias ll='ls -hl --color'
alias lla='ls -hal --color'
alias rm='rm -i'
alias grep='grep --color=auto'
alias chrome='chromium'
alias pacmans='pacman -Ss'
alias open='xdg-open'
alias openpic='feh -g 1280x720 -d -S'
alias feh='feh -g 1280x720'
alias ethlink='sudo ip l set enp0s20u2 up; sudo dhcpcd enp0s20u2'
alias dvorak='setxkbmap dvorak'
alias ao='setxkbmap us'
alias pptopdf='libreoffice --headless --invisible --convert-to pdf *.pptx'
alias docxpdf='libreoffice --headless -convert-to pdf *.docx'
alias excelpdf='libreoffice --headless -convert-to pdf *.docx'
alias latexeng='latexmk -pvc -pdf -interaction=batchmode -quiet -xelatex'
alias xauto='xrandr --output DP2 --auto'
alias xin='xrandr --output DP2 --auto'
alias xr='xrandr --output DP2 --right-of eDP1'
alias xout='xrandr --output DP2 --off'
alias ctl='systemctl'
alias emacs='emacs -nw'
alias copy='evilvte . &'

# Personal Programs
alias optstudy='cd /WPI/Documents/programming/Progrez\ project/OptimalStudy/build-OptimalStudy-Desktop-Debug/ && ./OptimalStudy'
alias ma='cd $(grep "" ~/bookmark)'
alias ba='echo -n \" > ~/bookmark && echo -n $(pwd) >> ~/bookmark && echo -n \" >> ~/bookmark'

# Networks
alias wifi='sudo wpa_supplicant -c ~/.config/CA/wpi_wireless.conf -i wlp3s0'
alias wifie='sudo wpa_supplicant -c ~/.config/CA/wpi_wireless_eduroam.conf -i wlp3s0 -D nl80211'
alias dwifi='sudo dhcpcd wlp3s0'
alias wifikill='sudo killall wpa_supplicant dhcpcd'
alias pingg='ping www.google.com'
alias pingg8='ping 8.8.8.8'
alias sshb='ssh bkayastha@ccc.wpi.edu'
alias sshg='ssh greenteam@ccc.wpi.edu'
alias sshe='ssh ieee@ece.wpi.edu'

alias mountWPI='sudo mount -t cifs //storage.wpi.edu/home ~/mnt/home -o username=bkayastha,uid=binam,gid=binam'
alias wifichk='ps aux | grep wpa && ps aux | grep dhc'
alias netstart='systemctl enable NetworkManager && systemctl start NetworkManager'
alias netkill='systemctl stop NetworkManager && systemctl disable NetworkManager'

# change directories
if [ -f ~/.directory_aliases ]; then
    . ~/.directory_aliases
fi
